version: 2
updates:
  # フロントエンドのnpm依存関係の更新設定
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "nov-sakamoto"

  # バックエンドのPython依存関係の更新設定
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "nov-sakamoto"

  # GitHubアクションの更新設定
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "nov-sakamoto" 